### ISSUE TITLE
pip install ./RolloutIW won't work

### ISSUE THREAD

**Issue by Kassandra-Rodriguez** [fred5577/VAE-IW#6]
After running pip install ./RolloutIW I get an error saying "it looks like the path or file doesn't exist"

**Comment by fred5577** [comment]
It just plain incorrect what I've written. You have go out of the "VAE-IW" folder and call "pip install VAE-IW". If you run into issues there it is probably because CMake is not installed

**Comment by Kassandra-Rodriguez** [comment]
Can you share the file structure so I can run the tool? We are getting an error saying "gym.error.NameNotFound: Environment Alien doesn't exist."

**Comment by Kassandra-Rodriguez** [comment]
> It just plain incorrect what I've written. You have go out of the "VAE-IW" folder and call "pip install VAE-IW". If you run into issues there it is probably because CMake is not installed
Can you share the file structure so I can run the tool? We are getting an error saying "gym.error.NameNotFound: Environment Alien doesn't exist."

**Comment by fred5577** [comment]
You have to install the atari environments. You can follow this guide: https://github.com/openai/gym/issues/1726#issuecomment-550580367

The gym environment has also change slightly, so I'll just changes a couple of things.
